#!/usr/bin/with-contenv sh

START_APACHE2=${START_APACHE2:-YES}
WWW_DATA_UID=${WWW_DATA_UID:-33}
WWW_DATA_GID=${WWW_DATA_GID:-33}

APACHE2_SERVER_NAME=${APACHE2_SERVER_NAME:-localhost}
APACHE2_SERVER_PORT=80

mkdir -p /var/www/default

# configure apache conf, www-data USER
if grep -q "\-SERVER_PORT\-" /etc/apache2/httpd.conf; then
    addgroup -g $WWW_DATA_GID www-data
    adduser -G www-data -g "www user" -D -h /var/www -s /sbin/nologin -u $WWW_DATA_UID www-data
    mkdir -p /var/www/webdav /var/lib/apache2 /var/log/apache2
    chown www-data:www-data /var/lib/apache2 /var/log/apache2
    echo "* configure httpd.conf"
    sed -i \
        -e "s#-SERVER_NAME-#${APACHE2_SERVER_NAME}#" \
        -e "s#-SERVER_PORT-#${APACHE2_SERVER_PORT}#" \
        /etc/apache2/httpd.conf
fi

if [ "$START_APACHE2" = "YES" ]; then
    rm /etc/services.d/apache2/down
fi
