FROM henne90gen/clang:18

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    libx11-dev \
    xorg-dev \
    xvfb
