name: forgejo-runner-image

on: push

jobs:
  build:
    name: "Build and Upload Image"
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u henne90gen -p $DOCKER_PASSWORD

      - name: Build Image
        run: just build-forgejo-runner-image

      - name: Test Image
        run: just test-forgejo-runner-image

      - name: Push Image
        run: just push-forgejo-runner-image
