name: osmtools

on: push

jobs:
  build:
    name: "Build and Upload Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u henne90gen -p $DOCKER_PASSWORD

      - name: Build Image
        run: make build-osmtools

      - name: Push Image
        run: make push-osmtools
